# All DebOps defaults are stored here.
# You should overwrite these values in either a group or host vars file.

ntp__timezone: 'Etc/UTC'

netbase__domain: '{{ ansible_domain }}'

nullmailer__state: 'latest'

pki_internal: False
pki_authorities: []

python__raw_apt_cache_valid_time: 0

wordpress__admin_email: 'londonatil@londonatil.london'
wordpress__admin_username: 'london'
wordpress__title: 'Debops'

wordpress__domain: commitcri.me

wordpress__table_prefix: 'la_wp_'

wordpress__disable_file_edit: True

wordpress__ssl: True

wordpress__varnish__add_ban_lurker_headers: True
wordpress__varnish__purge_conditions:
  'req.http.X-Purge-Method ~ "(?i)regex"': |
    ban("obj.http.X-Url ~ " + req.url + " && obj.http.X-Host == " + req.http.host);
    return (synth(200, "Purged"));

wordpress__varnish__vcl_recv_conditions:
  'req.url ~ "^/(cart|my-account|checkout|addons)" || req.url ~ "\?add-to-cart="': 'return (pass);'

  wordpress__plugins:
  - name: 'varnish-http-purge'
    state: 'latest'
  - name: 'elasticpress'
    state: 'latest'
  - name: 'redis-cache'
    state: 'latest'
  - name: 'tiny-compress-images'
    state: 'latest'
  - name: 'akismet'
    state: 'absent'
